= 20211009_workshop_geth_pending_logs

== Task

TODO: make changes in Geth source code around websocket subscriptions and verify the changes work

== Steps

. Get Geth client sources and compile
+
Geth sources are available at github at https://github.com/ethereum/go-ethereum
+
[source,bash]
----
git clone https://github.com/ethereum/go-ethereum
cd go-ethereum
make geth
----
+
After succesful compilation the Geth binaries can be found at `build/bin/`
+
[source,bash]
----
export PATH=$PATH:"$PWD/build/bin"
----
+
NOTE: the recommended steps to build on various OS are in the documentation at https://geth.ethereum.org/docs/install-and-build/installing-geth#build-go-ethereum-from-source-code
+
. Start Geth client on localhost
+
To start the Geth and then to "play" with the private network we need
+
.. To create an account(s) that can be pre-funded and used for transfers and contract calls
(see https://geth.ethereum.org/docs/interface/managing-your-accounts)
+
[source,bash]
----
mkdir data
DATADIR="$PWD/data"
geth account new --datadir "$DATADIR" --password <(echo 'P422wORd')
# note down the public address of the created key

# each account created stores a key in keystore under $DATADIR 
tree "$DATADIR"/keystore
----
+
NOTE: Supplying the password directly as part of the command line is not recommended
+
.. To define a genesis block and define the balance of the accounts
+
The genesis block is a `json` configuration that can be generated with `puppeth` binary
or copied as it is as an example from https://geth.ethereum.org/docs/interface/private-network#creating-the-genesis-block[documentation].
+
[source,bash]
----
./puppeth --network=myprivatenetwork
# console asks interactively about actions to take
# we want only the genesis block being generated

...

INFO [...] Administering Ethereum network           name=myprivatenetwork
WARN [...] No previous configurations found         path=$HOME/.puppeth/myprivatenetwork

What would you like to do? (default = stats)
 1. Show network stats
 2. Configure new genesis
 3. Track new remote server
 4. Deploy network components
> 2

What would you like to do? (default = create)
 1. Create new genesis from scratch
 2. Import already existing genesis
> 1

Which consensus engine to use? (default = clique)
 1. Ethash - proof-of-work
 2. Clique - proof-of-authority
> 1

Which accounts should be pre-funded? (advisable at least one)
> 0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9      
> 0x

Should the precompile-addresses (0x1 .. 0xff) be pre-funded with 1 wei? (advisable yes)
> n

Specify your chain/network ID if you want an explicit one (default = random)
> 
INFO [...] Configured new genesis block 

What would you like to do? (default = stats)
 1. Show network stats
 2. Manage existing genesis
 3. Track new remote server
 4. Deploy network components
> 2

 1. Modify existing configurations
 2. Export genesis configurations
 3. Remove genesis configuration
> 2

Which folder to save the genesis specs into? (default = current)
  Will create myprivatenetwork.json, myprivatenetwork-aleth.json, myprivatenetwork-harmony.json, myprivatenetwork-parity.json
> data/genesis
INFO [...] Saved native genesis chain spec          path=data/genesis/myprivatenetwork.json
INFO [...] Saved genesis chain spec                 client=aleth path=data/genesis/myprivatenetwork-aleth.json
INFO [...] Saved genesis chain spec                 client=parity path=data/genesis/myprivatenetwork-parity.json
INFO [...] Saved genesis chain spec                 client=harmony path=data/genesis/myprivatenetwork-harmony.json

> ^C
----
+
We defined the 'proof-of-work' to be used and made the address of the created
account to be pre-funded.
+
The configuraiton of the genesis block is exported under `data/genesis`
(`puppeth` stores the configuration under `$HOME/.puppeth/myprivatenetwork`).
.. Initialize Geth with the genesis block configuration
+
[source,bash]
----
geth init --datadir "$DATADIR" "$DATADIR"/myprivatenetwork.json
----
+
.. Starting Geth
+
see more at https://geth.ethereum.org/docs/interface/private-network
+
[source,bash]
----
geth \
  --datadir "$DATADIR" \
  --networkid 21110 -nodiscover \
  --unlock 0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9 --password <(echo 'P422wORd') --allow-insecure-unlock \
  -http --http.corsdomain '*' --ws --ws.origins='*' \
  --mine \
  --miner.threads=1 \
  --miner.etherbase=0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9
----
+
[cols="1,1"]
|===

| `--datadir "$DATADIR"`
| data directory with accounts

| `-networkid <id>`
| network identifier as defined in the genesis file (`chainId`, use the same)
  
| `-nodiscover`
| do not discover (not necessary, only one node here)

| `--unlock <address> --password <password-file> --allow-insecure-unlock`
| need to unlock account to be able to transfer from it
  
| `-http --http.corsdomain '*' --ws --ws.origins='*'`
| permit HTTP and WebSocket RPC + do not worry about CQRS (may connect eg. from Remix)

| `--http.api web3,eth,debug,personal,net`
| possible to restrict APIs available on HTTP RPC calls in console

| `--mine`
| to mine proof-of-work (defined in genesis block json configuration)
  
| `--miner.threads=1`
| to run at one CPU core
  
| `--miner.etherbase=<address>`
| to assign the rewards for mining to this address
|===
+
NOTE: unlock other accounts could be done in console with
`web3.personal.unlockAccount(<account>, <password>)`
+
NOTE: as a shortcut of running geth at localhost one may use
`geth --dev`
+
. Connect to JavaScript console of the started Geth node
+
[source,bash]
----
# via HTTP RPC
geth attach http://localhost:8545
# or via local IPC (inter-process-communication)
geth attach "$DATADIR/geth.ipc"
----
+
List available accounts and transfer funds
+
[source,javascript]
----
eth.accounts
eth.getBalance(eth.accounts[0])
eth.sendTransaction({from:"0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9", to:eth.accounts[1], value: "22", password: "P422wORd"})
web3.fromWei(eth.getBalance(eth.accounts[1]), "ether")
----
+
. Create a simple Solidity contract that emit log events
+
`EchoContract` is available at link:contracts/EchoContract.sol
+
. Build the contract
+
More details on building the Solidity contracts at https://docs.soliditylang.org/en/latest/installing-solidity.html
+
[source,bash]
----
docker run -v $PWD/contracts:/sources ethereum/solc:stable -o /sources/output --abi --bin /sources/EchoContract.sol
----
+
NOTE: mounting the volume with `podman` may throw `what():  boost::filesystem::status: Permission denied` use `:Z`
      at `-v $PWD/contracts:/sources:Z`
+
Compilation output can be found at directory `contracts/output`.
+
. Deploy contract
+
You can use https://medium.com/mercuryprotocol/dev-highlights-of-this-week-cb33e58c745f[Geth]
or use some GUI like https://remix.ethereum.org[Remix Ethereum] for the same task.
+
[quote, Quickly on deploying contract via Geth JavaScript console]
----
cat contracts/output/EchoContract.abi
abi = eth.contract(<abi-file-content--copy&paste>)

cat cat contracts/output/EchoContract.bin
bytecode = '0x<bin-file-content--copy&paste>'

deploy = {from:"0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9", data:bytecode, gas: 2000000}
undefined
contract = abi.new("TEST", deploy)

# check the contract address
contract.address
----
+
. Calling contract by calling with the transaction
+
[source,javascript]
----
eth.sendTransaction({from:"0x72B152b9cCC40BE2a04F4075a1457cF8f753F7c9", to:contract.address, value: "0"})
----




TODO: subscribe to events

https://eth.wiki/json-rpc/API#eth_newfilter

[source,javascript]
----
options = {
    fromBlock: 0,
    address: [],    // get events from specific addresses
    topics: []      // topics to subscribe to
};

options = {
    fromBlock: 0,
    
  "fromBlock": "0x1",
  "toBlock": "0x2",
  "address": "0x8888f1f195afa192cfee860698584c030f4c9db1",
  "topics": ["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b", null, ["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b", "0x0000000000000000000000000aff3454fce5edbc8cca8697c15331677e6ebccc"]]
}]

(err,event) => {
    if (!err)
    console.log(event)
}
----